language: cpp

dist: trusty osx

compiler:  
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install libjansson-dev

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make
