language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    compiler: clang
    
addons:
  apt:
    packages: libegl1-mesa-dev libgles2-mesa-dev libjansson-dev libsdl2-dev
  homebrew:
    packages: jansson sdl2
    
before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: cmake --build .
